config/routes.rb
Rails.application.routes.draw do
  root :to => "users#new"
  match "logout", to: "sessions#destroy", via: [:post, :get], as: "logout"
  match "login", to: "sessions#new", via: [:get], as: "login"
  resources :users
  resources :sessions
  match "home", to: "home#show", via: [:get, :post], as: "home"
  resources :home
  match "create_board", to: "boards#new", via: [:get]
  resources :boards
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :boards

  attr_accessor :password
  before_save :encrypt_password

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  def self.authenticate(email,password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < SessionsController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    @board.user = current_user
    if @board.save
      redirect_to home_url
    else
      flash.now.alert = @board.errors.full_messages
      render 'new'
    end
  end

  def show
    @boards = @current_user.boards
  end

  private

  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @boards = @current_user.boards
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ActionController::Base
  before_filter :require_login, except: [:new, :create]

  helper_method :current_user

  def create
    user = User.authenticate(params[:email], params[:password])
#    byebug
    if user
      session[:user_id] = user.id
      redirect_to home_url
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to root_url, notice: 'Logged out!'
  end

  def logged_in?
    !!current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  private

  def require_login
    return if logged_in?
    flash[:error] = 'You must be logged in to access this section'
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, :notice => "Signed Up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= form_for @board, html: {class: "signup_form"}  do |f| %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>

    <p class="button"><%= f.submit %></p>
<% end %>

app/views/home/show.html.erb
<p>Welcome to Dickbook</p>

<%= button_to "Create Board", create_board_path, method: :get %>
<% if @boards %>
  <% @boards.each do |board| %>
  Owner: <%= board.user.email %><br />
  Title: <%= board.title %><br /><br />
  <% end %>
<% else %>
  No boards to display. Create one!
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dickbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="user_nav">
  <% if current_user %>
    Logged in as <%= current_user.email %>
    <%= button_to "Sign out", logout_path, method: :post %>
  <% else %>
    <p>Not logged in</p>
    <%= link_to "Sign up", new_user_url %> or
    <%= link_to "Log in", login_url %>
  <% end %>
</div>

<% flash.each do |name, msg| %>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user, html: {class: "signup_form"} do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p class="button"><%= f.submit %></p>
<% end %>